### ISSUE TITLE
Timer for each question

### ISSUE THREAD

**Issue by Judahm147** [Judahm147/Bible-Quiz#1]
Add a timer for each question,just an ordinary countdown. E.g. 00:30 --> 00:29

**Comment by yrshaikh** [comment]
`Questions List.txt` is not committed.

**Comment by Judahm147** [comment]
I didn't finish all the questions yet. Feel free to add some. I have another repo that is meant to append additional MCQs to a file. If you can help with this issue though, I would appreciate it.

**Comment by Judahm147** [comment]
Simple timer with progress bar added
